#! /bin/csh -f

cd ..
./compile_all.csh

#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice0   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_PMP
#
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_PMP
#
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice1rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_PMP
#
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2ra   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_PMP
#
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid1_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid2_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_2km_slid3_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid1_SIASSA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid2_SIASSA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_DIVA_PMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_FCMP
#mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_NMP
mpiexec -n 2 IMAU_ICE_program   MISMIPplus/config-files/MISMIPplus_template_ice2rr   MISMIPplus/config-files/MISMIPplus_var_5km_slid3_SIASSA_PMP

