clc
clear all
close all

foldernames = {...
  'MISMIPplus_tuneGL_5km_Weertman_DIVA',...
  'MISMIPplus_tuneGL_5km_Weertman_hybrid',...
  'MISMIPplus_tuneGL_5km_Tsai2015_DIVA',...
  'MISMIPplus_tuneGL_5km_Tsai2015_hybrid',...
  'MISMIPplus_tuneGL_5km_Schoof2005_DIVA',...
  'MISMIPplus_tuneGL_5km_Schoof2005_hybrid',...
  'MISMIPplus_tuneGL_2km_Weertman_DIVA',...
  'MISMIPplus_tuneGL_2km_Tsai2015_DIVA',...
  'MISMIPplus_tuneGL_2km_Schoof2005_DIVA'};

for fi = 1: length(foldernames)
  foldername = foldernames{fi};
  filename = [foldername '/help_fields_ANT.nc'];
  time = ncread(filename,'time');
  ti = length(time);
  A_flow = ncread(filename,'A_flow_vav',[1,1,ti],[1,1,1]);
  disp(['Flow factor for experiment "' foldername '" is ' num2str(A_flow)]);
end