
# Adjust MYLIB and MYINC such that they match with the libraries and include paths:
  MYLIB  = /usr/lib64/
  MYLIB2 = /nethome/beren017/IMAU_ICE/src_v1.1.1/
  MYINC  = /usr/lib64/gfortran/modules/

# Compiler names:
  F90 = mpifort

# Compiler flags:
##  F90FLAGS = -g -O2 -I $(MYINC) -J$(MOD_PATH) -Wall -fdump-core -fbounds-check -fcheck-array-temporaries -ffree-line-length-none
  F90FLAGS = -g -O3 -I $(MYINC) -J$(MOD_PATH) -ffree-line-length-none

# Link flags:
  LDFLAGS = -lz -lnetcdff -lnetcdf -L$(MYLIB) -L$(MYLIB2) -llapack -lpthread
